spring:

  application:
    name: TaskManager

  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080